version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
