version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
      target: production
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
