version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
