version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/backend:/app/src/backend
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
    command: [ "npx", "nodemon", "--watch", "src/backend", "--exec", "node", "--loader", "ts-node/esm", "src/backend/server.ts" ]